version: "3"
services:
  api-server:
    image: api-server
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - server-db
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - server-db
    volumes:
      - mongo-data:/data/db
networks:
  server-db:
    driver: bridge
volumes:
  mongo-data:
    driver: local
